### ISSUE TITLE
I'd love to contribute.

### ISSUE THREAD

**Issue by rakesh-verma-16** [ParallelDots/ParallelDots-Python-API#4]
Hi, I just went through the basic API and would love to contribute to the project. Is the project Open Source and if yes, i'd like to learn and contribute to it. I'm creating the issue here because i have found it to be working almost everytime. Pardon :)

**Comment by juggernauts** [comment]
Hi Rakesh,
The project is not currently open-source, this repository is just a python wrapper over our API. Thanks for your interest :)
