### ISSUE TITLE
can't import abuse module

### ISSUE THREAD

**Issue by dimple1024** [ParallelDots/ParallelDots-Python-API#5]
i was trying to use paralleldots to detect abusive content in the text so here is what i did:
>>from paralleldots import abuse
but i got an  error: ImportError: cannot import name abuse
i have 0.9.1 version of paralleldots installed and python 2.7

**Comment by dimple1024** [comment]
@ahwankumar sir plz have a look at the issue

**Comment by ahwankumar** [comment]
@Meghdeep Please have a look at this case.

**Comment by shruti9619** [comment]
There's no api endpoint given in the documentation for abusive content check.

**Comment by shuttlesworthNEO** [comment]
I have submitted a PR for the same. Please check.

**Comment by shruti9619** [comment]
I added the api endpoint and the python code to fetch it successfully through pull request could you review it?

**Comment by Meghdeep** [comment]
Hey shruti, we're completely revamping our APIs and will have a completely new wrapper up, the abuse endpoint will be added in when that rolls out this weekend. Thanks a lot for your interest !

**Comment by shruti9619** [comment]
Excited to see the change.

**Comment by dimple1024** [comment]
sir i am trying to use the abuse method but i am facing the same issue.

**Comment by Meghdeep** [comment]
Please upgrade the existing pip installation with: sudo pip install paralleldots --upgrade
The issue has been rectified.
